- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "devops with aws"
    DURATION: 120hrs
    STUDENT: jyothi
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, student is {{ STUDENT }}"

 