- name: variables
  hosts: local
  connection: local
  vars:  
    course: "devops with aws"
    duration: 120hrs
    student: jyothi
  tasks:
- name: print the variable
  ansible.builtin.debug:
    msg: "course is {{ course }}, duration is {{ duration }}, student is {{ student }}"