- name: variables from files
  hosts: local
  connection: local
  vars_files:  # it is a module for var files
  - variables.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, student is {{ STUDENT }}"