- name: variables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
  - name: DURATION
    prompt: please enter Duration
  - name: STUDENT
    prompt: please enter student name
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "course is {{ COURSE }}, duration is {{ DURATION }}, student is {{ STUDENT }}"