- name: devops course information
  hosts: local
  connection: local
  vars: 
    course_name: devops # string 
    duration: 120 # number
    topics: # list
    - linux 
    - shell
    - ansible
    - aws
    live: true # boolean
    tools:  #map
      ci: jenkins
      cloud: aws
      containerization: docker
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "hello i am learning {{ course_name }},  {{ duration }},  {{ topics }},  {{ live }},  {{ tools }}"

