- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if RHEL #for RHEL == Redhat 
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "Redhat"   # condition

    - name: install nginx if ubuntu  # for ubuntu == debian 
    ansible.builtin.apt module:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"    # condition


    

