- name: convert map to list
  hosts: local
  connection: local
  tasks:
  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: siva
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

