- name: convert map to list
  hosts: local
  connection: local
  tasks:
  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10hrs
        trainer: siva
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"  # function


  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'siva'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"      # function
    
