- name: convert map to list
  hosts: local
  connection: local
  tasks:
  - name: convert upper to lower
    vars:
      name: "PRAyakshA KOTA"
    ansible.builtin.debug:
      msg: "hello {{ name | lower }}"  # function



- name: convert lower to upper
  vars:
    name: "PRAyakshA kota"
  ansible.builtin.debug:
    msg: "hello {{ name | upper }}"  # function



